### ISSUE TITLE
Reproducing MuSA algorithm

### ISSUE THREAD

**Issue by devisperessutti** [SveinnEirikur/s2-sr-parameter-optimization#3]
Hello and thank you for this great repository!

I would like to reproduce the MuSA algorithm but it seems that only the wrapper code is provided and not the original Matlab code (no link in the Installation section like for ATRPK)? Am I missing something?

**Comment by SveinnEirikur** [comment]
Hello, and thank you for your interest. I am delighted to hear that this work is helpful to others.

I believe I got the code for the MuSA implementation directly from that paper's lead author, Dr. C. Paris. I don't feel comfortable distributing it as it is not my code. If it is still not available publicly, I suggest contacting her directly. Her contact details can be found here: https://people.utwente.nl/c.paris. I am sure she will also be happy about your interest in her work.

Sincerely,
Sveinn
________________________________
From: Devis Peressutti ***@***.***>
Sent: Tuesday, August 20, 2024 2:09 PM
To: SveinnEirikur/s2-sr-parameter-optimization ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SveinnEirikur/s2-sr-parameter-optimization] Reproducing MuSA algorithm (Issue #3)


Hello and thank you for this great repository!

I would like to reproduce the MuSA algorithm but it seems that only the wrapper code is provided and not the original Matlab code (no link in the Installation section like for ATRPK)? Am I missing something?

**Comment by devisperessutti** [comment]
Thank you @SveinnEirikur !

I will contact her directly.

Best,
Devis
